// Assembles the web app for both the server (./public) and the Android app (../assets):
// the app page, the legal pages, self-hosted fonts, and a Content-Security-Policy that only
// allows the exact inline scripts in these pages (by SHA-256 hash).
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";

const root = path.resolve(import.meta.dirname, "..");
const style = `<style>\n${fs.readFileSync(path.join(root, "legal/_style.css"), "utf8")}</style>`;
const pages = {
  "index.html": fs.readFileSync(path.join(root, "app.html"), "utf8"),
  "privacy.html": fs.readFileSync(path.join(root, "legal/privacy.html"), "utf8").replace("<!--STYLE-->", style),
  "terms.html": fs.readFileSync(path.join(root, "legal/terms.html"), "utf8").replace("<!--STYLE-->", style),
};

const hashes = new Set();
for (const html of Object.values(pages)) {
  for (const m of html.matchAll(/<script>([\s\S]*?)<\/script>/g)) {
    hashes.add(`'sha256-${crypto.createHash("sha256").update(m[1]).digest("base64")}'`);
  }
  if (/<script[^>]*src=/.test(html)) throw new Error("External scripts aren't allowed by the CSP");
}
const csp = [
  "default-src 'self'",
  `script-src ${[...hashes].join(" ") || "'none'"}`,
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: blob:",
  "font-src 'self'",
  "connect-src 'self' https://api.github.com",
  "object-src 'none'",
  "base-uri 'none'",
  "form-action 'self'",
  "frame-ancestors 'none'",
].join("; ");

for (const out of [path.join(root, "server/public"), path.join(root, "assets")]) {
  fs.rmSync(out, { recursive: true, force: true });
  fs.mkdirSync(path.join(out, "fonts"), { recursive: true });
  for (const [name, html] of Object.entries(pages)) fs.writeFileSync(path.join(out, name), html);
  for (const f of fs.readdirSync(path.join(root, "fonts"))) fs.copyFileSync(path.join(root, "fonts", f), path.join(out, "fonts", f));
}
fs.writeFileSync(path.join(root, "assets/csp.txt"), csp);
fs.writeFileSync(path.join(root, "server/src/csp.generated.js"),
  `// Generated by build.mjs — do not edit.\nexport const CSP = ${JSON.stringify(csp)};\n`);
console.log(`Built pages with ${hashes.size} script hash(es).`);
